services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=batch
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo-data:/mongo-data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tweets
  neo4j:
    image: neo4j:latest
    restart: always
    ports:
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-My-Cookies"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"