services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=batch
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo-data:/mongo-data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tweets