rootProject.name = "spring-batch-practice"

include("hello-world")
include("simple-job-step")
include("conditional-job")
include("flow-job")
include("customize-job-repository")
include("job-explorer")
include("run-job-launcher")
include("account-transaction-job")
include("customer-item-reader")
include("customer-item-processor")
include("customer-item-writer")
include("apress-banking-expample")
include("optimization-batch")
