spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  docker:
    compose:
      lifecycle-management: start_only
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
decorator:
  datasource:
    p6spy:
      enable-logging: true