spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  docker:
    compose:
      lifecycle-management: start_only
  batch:
    jdbc:
      initialize-schema: always
decorator:
  datasource:
    p6spy:
      enable-logging: true

job:
  resource-path: s3://devyonghee/inputs/*.csv

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    region:
      auto: false
      static: ap-northeast-2
