spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: password
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  sql:
    init:
      platform: mysql
      mode: never
  docker:
    compose:
      lifecycle-management: start_only
  batch:
    jdbc:
      initialize-schema: never
    job:
      name: ${job.name:NONE}
  data:
    mongodb:
      username: root
      password: password
      database: customers
      host: localhost
      port: 27017
decorator:
  datasource:
    p6spy:
      enable-logging: true