spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  docker:
    compose:
      lifecycle-management: start_only
  batch:
    jdbc:
      initialize-schema: always
    job:
      name: conditionalStepLogicJob
